apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payguard-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhil1232/production-grade-fastapi-platform.git
    targetRevision: main
    path: charts/fastapi
    helm:
      values: |
        replicaCount: 2
        image:
          repository: ghcr.io/akhil1232/production-grade-fastapi-platform/payguard-ai
          tag: 739157345dbb34f8c6a78143b113a619b595f3e2056caff21f3f9f788285ff54
          pullPolicy: Always
        imagePullSecrets:
          - name: ghcr-secret
        service:
          type: ClusterIP
          port: 8000
  destination:
    server: https://kubernetes.default.svc
    namespace: payguard-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true